export type Model = {slug:string;name:string;provider:string;overall:number;reasoning:number;coding:number;agentic:number;multi:number;speed:number;input:number;output:number;context:string;scope:string;updated:string;best:string[]};
export const models: Model[] = [
 {slug:"gpt-5",name:"GPT-5",provider:"OpenAI",overall:96,reasoning:97,coding:95,agentic:96,multi:94,speed:74,input:1.25,output:10,context:"400K",scope:"示例：需接駁官方/獨立 benchmark API 驗證",updated:"2026-08-07",best:["Agent","Coding","Research"]},
 {slug:"claude-opus-4-1",name:"Claude Opus 4.1",provider:"Anthropic",overall:95,reasoning:96,coding:97,agentic:95,multi:91,speed:65,input:15,output:75,context:"200K",scope:"示例：需接駁 Anthropic/benchmark 來源",updated:"2026-08-07",best:["Coding","Long-form","Agent"]},
 {slug:"gemini-2-5-pro",name:"Gemini 2.5 Pro",provider:"Google",overall:93,reasoning:94,coding:91,agentic:90,multi:96,speed:70,input:1.25,output:10,context:"1M+",scope:"示例：需接駁 Google/benchmark 來源",updated:"2026-08-07",best:["Long context","Multimodal","Research"]},
 {slug:"deepseek-r1",name:"DeepSeek R1",provider:"DeepSeek",overall:88,reasoning:94,coding:84,agentic:82,multi:86,speed:78,input:.55,output:2.19,context:"128K",scope:"示例：需驗證最新價格",updated:"2026-08-07",best:["Reasoning value","Cheap API"]},
 {slug:"qwen3-coder",name:"Qwen3 Coder",provider:"Alibaba / Qwen",overall:86,reasoning:84,coding:92,agentic:85,multi:90,speed:82,input:.3,output:1.2,context:"256K",scope:"示例：需驗證最新來源",updated:"2026-08-07",best:["Coding value","中文"]}
];
export const news = [
 {id:"n1",title:"OpenAI 發布新 Agent 開發工具更新",summary:"官方更新令開發者更容易建立可執行任務的 AI Agent。本文只保存摘要與來源連結，不複製全文。",why:"Agent 工具鏈會直接影響企業自動化與開發成本。",source:"OpenAI Blog",url:"https://openai.com/news/",time:"今日 09:10",cat:"Agent",hk:false},
 {id:"n2",title:"香港政府公布 AI 治理及數碼轉型新措施",summary:"本地政策焦點集中於公共服務、數據治理及企業採用 AI 的風險管理。",why:"香港用家及中小企需要了解合規與資助方向。",source:"HKSAR / OGCIO",url:"https://www.digitalpolicy.gov.hk/",time:"今日 11:30",cat:"香港 AI",hk:true},
 {id:"n3",title:"開源模型社群推出新一代 Coding Model",summary:"新模型主打程式碼生成、修復與 repo-level reasoning。實際排名需等待獨立 benchmark。",why:"可能降低中小企使用 coding agent 的成本。",source:"Hugging Face",url:"https://huggingface.co/models",time:"昨日 22:00",cat:"Model",hk:false},
 {id:"n4",title:"MCP Registry 新增多個官方資料庫連接器",summary:"更多資料庫 MCP Server 令 Agent 可以更安全地接駁企業資料。",why:"MCP 生態成熟會加快 AI Agent 落地。",source:"Model Context Protocol",url:"https://modelcontextprotocol.io/",time:"昨日 18:20",cat:"MCP",hk:false}
];
export const categories=["Design & Creative","Coding & Development","Research & Search","Data & Analytics","Database","AI / ML / Agents","DevOps & Cloud","Documents & Office","Productivity","Security"];
export type Ext={slug:string;name:string;type:"Skill"|"MCP";cat:string;desc:string;publisher:string;official:string;stars:number;momentum:number;trust:"Official"|"Trusted Community"|"Community"|"Warning";updated:string;permissions:string[];install:string;source:string;compat:string[]};
export const extensions:Ext[]=[
 {slug:"github-mcp",name:"GitHub MCP Server",type:"MCP",cat:"Coding & Development",desc:"俾 Agent 讀取 repo、issue、PR 等 GitHub 工作流程。",publisher:"GitHub / Community",official:"需驗證",stars:18000,momentum:88,trust:"Trusted Community",updated:"2026-08-06",permissions:["GitHub repositories","OAuth/API token"],install:"未發布：接駁官方 registry 後顯示已驗證命令",source:"https://github.com/modelcontextprotocol/servers",compat:["Hermes Agent","Claude Desktop","Cursor"]},
 {slug:"frontend-design",name:"Frontend Design Skill",type:"Skill",cat:"Design & Creative",desc:"教 Agent 建立有清晰美學方向、可用、responsive 的高質前端 UI。",publisher:"Open Design / Anthropic-adapted",official:"Bundled/Installed",stars:0,momentum:78,trust:"Official",updated:"2026-08-07",permissions:["Project files"],install:"hermes skills inspect frontend-design",source:"local Hermes Skills",compat:["Hermes Agent"]},
 {slug:"arxiv",name:"arXiv Research Skill",type:"Skill",cat:"Research & Search",desc:"搜尋 arXiv 論文、整理研究方向與 citation 線索。",publisher:"Hermes Skills",official:"Installed",stars:0,momentum:65,trust:"Official",updated:"2026-08-07",permissions:["Web search"],install:"hermes skills inspect arxiv",source:"local Hermes Skills",compat:["Hermes Agent"]},
 {slug:"postgres-mcp",name:"PostgreSQL MCP",type:"MCP",cat:"Database",desc:"讓 Agent 透過 MCP 查詢 PostgreSQL；適合數據分析但權限要嚴格限制。",publisher:"MCP Community",official:"Community",stars:6200,momentum:72,trust:"Community",updated:"2026-08-02",permissions:["Database","Credentials"],install:"未發布：等待官方 registry/README 驗證",source:"https://modelcontextprotocol.io/",compat:["Hermes Agent","Claude Desktop"]}
];
export function valueScore(m:Model, weights={quality:.5,cost:.3,speed:.2}){const quality=(m.overall+m.coding+m.agentic+m.reasoning)/4; const cost=100/(1+m.input+m.output); return +(quality*weights.quality+cost*weights.cost+m.speed*weights.speed).toFixed(1)}
export function trendingScore(e:Ext){const freshness=90; const pop=Math.log10(e.stars+10)*18; const trust=e.trust==='Official'?100:e.trust==='Trusted Community'?82:e.trust==='Community'?58:20; return Math.round(e.momentum*.45+pop*.2+freshness*.2+trust*.15)}
